name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install go
      uses: actions/setup-go@v4

    - name: Go test
      run: |
        go test -coverprofile cover.out -v ./...
        go tool cover -func cover.out
        # go test -v -covermode=count -coverprofile=coverage.out

    - name: Go example
      run: |
        cd example
        go run .

    - name: Go install
      run: |
        go install
        ls -la $GOPATH
